name: juejin
description: Xitu Juejin APP on Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  collection: ^1.16.0
  cookie_jar: ^3.0.1
  device_info_plus: ^8.0.0
  diox: ^5.0.0-dev.1
  diox_cookie_manager: ^2.0.0
  equatable: ^2.0.3
  extended_sliver: ^2.1.3
  extended_text: ^10.0.0
  ff_annotation_route_library: ^3.0.0
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.4.0
  flutter_inappwebview: ^5.4.3+7
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  intl: any
  json_annotation: ^4.6.0
  loading_more_list: ^4.1.2
  logging: ^1.0.2
  oktoast: ^3.2.0
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  pull_to_refresh_notification: ^2.3.0
  url_launcher: ^6.1.5
  visibility_detector: ^0.3.3

dev_dependencies:
  archive: ^3.3.0
  args: ^2.3.1
  build_runner: ^2.2.0
  crypto: ^3.0.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  path: ^1.8.1
  process_run: ^0.12.3+2
  yaml: ^3.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/icon/post/
    - assets/icon/user/
    - assets/icon/topic/
